# Generated by Django 4.1.2 on 2022-10-12 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name': 'Agente', 'verbose_name_plural': 'Agentes'},
        ),
    ]
